[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cpsat-dbap"
version = "0.1.0"
description = "CPSAT DBAP solver"
requires-python = ">=3.12"

dependencies = [
    "ortools>=9.15",
    "pandas>=3.0",
    "numpy>=2.4",
    "matplotlib>=3.10.8",
]
